services:
  goboard:
    build: .
    volumes:
      - board-data:/app/data

  caddy:
    image: caddy:2-alpine
    ports:
      # - "443:443"
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
    depends_on:
      - goboard

volumes:
  board-data:
  caddy-data:
